### PR TITLE
feat: emb dim for client

### PR DESCRIPTION
**Pull request by zanussbaum**
```
>>> len(embed.text(["hi i'm a walrus"], dimensionality=384, model="nomic-embed-text-v1.5")["embeddings"])
1
>>> len(embed.text(["hi i'm a walrus"], dimensionality=384, model="nomic-embed-text-v1.5")["embeddings"][0])
384
>>> len(embed.text(["hi i'm a walrus"], dimensionality=128, model="nomic-embed-text-v1.5")["embeddings"][0])
128
>>> len(embed.text(["hi i'm a walrus"], dimensionality=64, model="nomic-embed-text-v1.5")["embeddings"][0])
WARNING:root:Dimensionality 64 is less than the suggested of 128. Performance may be degraded.
64
````

### CODE REVIEW

**Comment by AndriyMulyar** [comment]
please bump version number

**Review by apage43 — APPROVED** [review]
lgtm - also run a test to make sure you get an error when trying to do with v1 at less than 768?

**Comment by zanussbaum** [comment]
```
>>> embed.text(["hi i'm a walrus"], dimensionality=384)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zach/Documents/Github/nomic/nomic/embed.py", line 99, in text
    response = future.result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/zach/Documents/Github/nomic/nomic/embed.py", line 61, in text_api_request
    raise Exception((response.status_code, response.text))
Exception: (412, '{"detail":"Unsupported dimensionality 384 for model \'nomic-embed-text-v1\' (supported: 768)"}')
```

**Comment by zanussbaum** [comment]
@AndriyMulyar @apage43 i don't have perms to push to main, if this looks good to you guys can one of you please?

**Comment by AndriyMulyar** [comment]
Version bump please

**Review by AndriyMulyar — APPROVED** [review]

**Comment by apage43** [comment]
it's bumped, check diff

**Pull request merged**
