### PR TITLE
small embedding fixes

### PR DESCRIPTION
**Pull request by zanussbaum**
* removes libcairo
* returns model name in api request

### CODE REVIEW

**Review by cebtenzzre — APPROVED** [review]

**Review by apage43 — APPROVED** [review]

**Comment by zanussbaum** [comment]
I'm not authorized to merge this @apage43 are you able to?

**Comment by apage43** [comment]
> I'm not authorized to merge this @apage43 are you able to?

ah I am not - I think only @AndriyMulyar and @bmschmidt reviews actually count on this repo

**Review by AndriyMulyar — APPROVED** [review]

**Comment by bmschmidt** [comment]
Merged.

**Comment by bmschmidt** [comment]
We should get @apage43 and @etaldot permissions here too, yeah.

**Pull request merged**
